### ISSUE TITLE
open source feeder docker image

### ISSUE THREAD

**Issue by fluffydonkey** [Team-Kujira/pond#1]
Is it possible to open source the docker images? It would be great to see how the whitelist for the oracle module is setup.

**Comment by volstas** [comment]
https://github.com/Team-Kujira/pond-images/blob/main/feeder/Dockerfile looks like this is the feeder?

**Comment by starsquidnodes** [comment]
You can find the Dockerfilese here: https://github.com/Team-Kujira/pond-images
and the feeder config here: https://github.com/Team-Kujira/pond/blob/main/pond/templates/config/kujira/feeder.toml
